# Generated by Django 5.0.6 on 2024-06-21 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_useraddrees'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام استان')),
            ],
            options={
                'verbose_name_plural': 'استان',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80, verbose_name='نام و نام خانوادگی')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('post_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=12, verbose_name='تلفن')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس کاربران',
            },
        ),
        migrations.DeleteModel(
            name='UserAddrees',
        ),
    ]
