# Generated by Django 5.0.6 on 2024-06-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_city_useraddress_delete_useraddrees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='post_code',
            new_name='postal_code',
        ),
    ]
