# Generated by Django 5.0.6 on 2024-06-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default=1, max_length=40, verbose_name='کد استان'),
            preserve_default=False,
        ),
    ]
