# Generated by Django 5.0.6 on 2024-06-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_city_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='code',
        ),
    ]
