# Generated by Django 5.0.6 on 2024-07-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
