# Generated by Django 5.0.6 on 2024-06-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
    ]
