# Generated by Django 5.0.6 on 2024-06-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_information_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
        ),
    ]
