# Generated by Django 5.0.6 on 2024-06-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_specifications_property_product_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
