# Generated by Django 5.0.6 on 2024-07-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_color_alter_product_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.discount_order', verbose_name='تخفیف'),
        ),
    ]
