# Generated by Django 5.0.6 on 2024-07-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_discount_order_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_order',
            name='discount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
