# Generated by Django 5.0.6 on 2024-07-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_orderitem_discount'),
        ('product', '0016_alter_discount_order_discount_alter_product_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount_Order',
        ),
    ]
