# Generated by Django 5.0.6 on 2024-07-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_category_image_alter_product_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
