# Generated by Django 5.0.6 on 2024-07-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(related_name='gallery', to='product.gallery', verbose_name='تصایر'),
        ),
    ]
