# Generated by Django 5.0.6 on 2024-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_color_title_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ قبل تخفیف'),
        ),
    ]
