# Generated by Django 5.0.6 on 2024-07-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(blank=True, default=0, help_text='این فیلد اجباری نیست', null=True, verbose_name='مبلغ قبل تخفیف'),
        ),
    ]
