# Generated by Django 5.0.6 on 2024-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='رمز تحفیف')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='تعداد')),
            ],
        ),
    ]
