# Generated by Django 5.0.6 on 2024-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
