# Generated by Django 5.0.6 on 2024-07-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_delete_discountcode_order_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
    ]
