# Generated by Django 5.0.6 on 2024-07-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_order_discount_amount'),
        ('product', '0015_discount_order_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.discount_order'),
            preserve_default=False,
        ),
    ]
