# Generated by Django 5.0.6 on 2024-07-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_orderitem_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
    ]
